derickwarshaw/jenkins

CONTRIBUTING.md

Added some basic information to break ground. Ideally this file should make it easy for contributors and on the fence would-be contributors to know the basic guidelines for getting started.
No verification steps

Add CONTRIBUTING.md to project

---

README.md
contributing.json
index.android.js

- Added link to README pointing to CONTRIBUTION.md
- Made the Gitmagic rules less...abrasive

- Made an update to README and calmed down some gitmagic rules

---

App/Fixtures/README.md
App/Fixtures/getViews.json

project cleanup
no verification steps

Project Cleanup

---

LICENSE.md

I just realized I forgot to change the name. Sorry about that!
I guess, that happens when you quickly copy a license from another project.
I changed the name to "Derick Warshaw". Does that fit?

updated the license holder's name

---

README.md

- Pointing to react docs for the time being

Update Startup Instructions

---

App/Reducers/LoginReducer.js

Resolved bug that shows instance name on home screen after login failure

---

README.md

- Added docs generated from ESDocs to be available at the project's github page
- Added link to README that points the user to the docs [https://derickwarshaw.github.io/jenkins/]

Added link to README.md for docs

---

CONTRIBUTING.md

- Added instructions in CONTRIBUTING.md on how to run tests

Add instructions on how to run tests

---

package.json

babel-preset for ES6 React-native

install babel

---

Tests/Components/AlertMessageComponentTest.js
Tests/Setup.js
package.json

Added AlertMessageComponent unit tests for issue #69

Added AlertMessageComponent unit tests

---

App/Components/AlertMessageComponent.js
App/Components/FullButton.js
App/Components/RoundedButton.js

Before I continue to refactor the other components can one of you React wizards verify that I have done this correctly?
@derickwarshaw @bbohen @nicholas-b-carter @Daadler6

#71 refactored to stateless component

---

Tests/Sagas/LoginSagaTest.js

Added LoginSaga unit tests for issue #62

Added LoginSaga unit tests

---

Tests/Sagas/GetJobsSagaTest.js

Added GetJobsSaga unit tests for issue #61

Added GetJobsSaga unit tests

---

Tests/Sagas/GetBuildsSagaTest.js

Added getBuildsSaga unit test for issue #60

Added getBuildsSaga unit test

---

package.json

chore(package): update redux-logger to version 2.7.4

---

package.json

chore(package): update redux-saga to version 0.12.1

---

package.json

chore(package): update nyc to version 8.3.2

---

package.json

chore(package): update eslint-plugin-react to version 6.5.0

---

package.json

chore(package): update enzyme to version 2.5.1

---

package.json

chore(package): update nyc to version 8.4.0

---

package.json

chore(package): update react-native-router-flux to version 3.37.0

---

package.json

chore(package): update enzyme to version 2.6.0

---

package.json

chore(package): update eslint-plugin-react to version 6.6.0

---

package.json

fix(package): update react-native-animatable to version 1.1.0

---

package.json

chore(package): update esdoc to version 0.5.1

---

package.json

fix(package): update seamless-immutable to version 7.0.1

---

package.json

fix(package): update redux-persist to version 4.0.1

---

App/Containers/DrawerContent.js

- Only display the option to view builds or jobs if they are available

Only Showing Link When Jobs or Builds Have Length

---

package.json

fix(package): update react-native to version 0.41.2

---

package.json

chore(package): update esdoc to version 1.0.0-alpha.2

---

package.json

fix(package): update redux-saga to version 0.15.3

---

package.json

fix(package): update react-native to version 0.46.0
